---
- hosts: devhaproxy
  gather_facts: true
  become: yes
  tags: haproxy
  tasks:
    - name: Deploy HAproxy
      package:
        name: haproxy
        state: present

- hosts: webservers
  gather_facts: true
  become: yes
  tags: webservers
  tasks:
    - name: Deploy NginX
      package:
        name: nginx
        state: present
    
    # - name: Place index file. Use role??

    # - name: Start NginX server
    #   systemd:
    #     name: nginx
    #     enabled: yes
    #     state: started

    # - name: Wait for server to start
    #   wait_for:
    #     port: 80

    # block:
    #   - name: Test three requests, webservers A, B, and C should reply
    # http get request