---
- hosts: devhaproxy
  gather_facts: no
  become: yes
  tags: haproxy
  tasks:
    - name: Deploy HAproxy
      package:
        name: haproxy
        state: present

    - name: Copy HAproxy configuration
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

- hosts: webservers
  gather_facts: no
  become: yes
  tags: webservers
  tasks:
    - name: Install NginX
      package:
        name: nginx
        state: present

    - name: Start NginX
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Install PHP-fpm
      package:
        name: php7.4-fpm
        state: present
      
    - name: Start PHP
      service:
        name: php7.4-fpm
        state: started
        enabled: yes

    - name: Copy NginX site configuration
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: Copy PHP application
      copy:
        src: index.php
        dest: /var/www/html/index.php

    # restart PHP before nginx, could cause a problem otherwise
    - name: Restart PHP
      service:
        name: php7.4-fpm
        state: restarted
    
    - name: Restart NginX server
      service:
        name: nginx
        state: restarted

    # likely not necessary, wait time is probably very quick
    - name: Wait for server to start
      wait_for:
        port: 80

# - hosts: devhaproxy
#   gather_facts: no
#   become: yes
#   tags: devhaproxy
#   tasks:
    # - name: First GET request
    #   get_url:
    #     url: 10.6.0.5
    # - name: First GET request
    #   uri:
    #     url: http://www.example.com
    #     return_content: yes
    #   register: webpage
    #   debug:
    #     var: webpage