---
- name: Deploy HAproxy
  hosts: devhaproxy
  gather_facts: no
  become: yes
  tags: haproxy
  tasks:
    - name: Install HAproxy
      package:
        name: haproxy
        state: present

    - name: Copy HAproxy configuration
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

- name: Deploy NginX and PHP
  hosts: webservers
  gather_facts: no
  become: yes
  tags: webservers
  tasks:
    - name: Install NginX
      package:
        name: nginx
        state: present

    - name: Start NginX
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Install PHP-fpm
      package:
        name: php7.4-fpm
        state: present
      
    - name: Start PHP
      service:
        name: php7.4-fpm
        state: started
        enabled: yes

    - name: Copy NginX site configuration
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: Copy PHP application
      copy:
        src: index.php
        dest: /var/www/html/index.php

    # restart PHP before nginx, could cause a problem otherwise
    - name: Restart PHP
      service:
        name: php7.4-fpm
        state: restarted
    
    - name: Restart NginX server
      service:
        name: nginx
        state: restarted

    # likely not necessary, wait time is probably very quick
    - name: Wait for server to start
      wait_for:
        port: 80

# testing
- name: Finding the IP of devhaproxy for testing
  hosts: devhaproxy   # devhaproxy or bastion sends a request to public IP of devhaproxy
  gather_facts: yes
  become: yes
  tags: devhaproxy
  tasks:
    - name: Identify public IP of devHAproxy (Ansible goes trhough the bastion, and only knows devHAproxy's private IP address)
      uri:
        url: https://api.ipify.org?format=json
        return_content: yes
      register: ip_response
    
    - name: print IP
      debug: var=ip_response

- name: Testing
  hosts: localhost
  tasks:
    - name: First GET request
      shell: msg="curl {{devHA_IP}}"

# ansible -m debug -a msg="{{ '-'.join(('list', 'joined', 'together')) }}" localhost

    # - name: First GET request
    #   shell: msg="curl {{devHA_IP}}"

    # - name: Second GET request
    #   shell: 'curl ' + devHA_IP

    # - name: Third GET request
    #   shell: 'curl ' + devHA_IP