---
- hosts: devhaproxy
  gather_facts: true
  become: yes
  tags: haproxy
  tasks:
    - name: Deploy HAproxy
      package:
        name: haproxy
        state: present

    - name: Copy HAproxy configuration
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

- hosts: webservers
  gather_facts: true
  become: yes
  tags: webservers
  tasks:
    - name: Deploy NginX
      package:
        name: nginx
        state: present

    - name: Copy NginX configuration
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Copy PHP application
      copy:
        src: index.php
        dest: /var/www/html/index.php

    - name: Start NginX server
      service:
        name: nginx
        state: started

    # - name: Wait for server to start
    #   wait_for:
    #     port: 80

    # block:
    #   - name: Test three requests, webservers A, B, and C should reply
    # http get request